version: '3.8'
services:
  uc-service:
    image: harbor.ceasefire.rid-intrasoft.eu/certh_marketplaces/social_media_scraper:latest
    container_name: use-case5
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - social_media_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb-usecase5
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - social_media_network

networks:
  social_media_network:
    driver: bridge
