version: '3.8'
services:
  uc-service:
    image: iti-gitlab.iti.gr:5050/ceasefire/use_case_5:1.0.0 
    container_name: use-case5
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - my_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge